- name: Install packages.
  package:
    name:
    - python3-setuptools
    - python3-pip

- name: configure pip.
  template:
    src: "templates/etc/pip.conf.j2"
    dest: "/etc/pip.conf"
    mode: 0644
  when:
    - python_global_index_url is defined

- name: Install setuptools # noqa 403
  pip:
    name: setuptools
    state: latest

- name: Upgrade pip # noqa 403
  pip:
    name: pip
    state: latest

- name: Install pip packages.
  pip:
    name: "{{ python_pip_packages }}"